# Generated by Django 3.0.5 on 2020-04-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='', max_length=20)),
                ('time', models.TimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='schedule',
            field=models.ManyToManyField(to='listings.Schedule'),
        ),
    ]
